"""TikTok discovery engine: search -> candidate creator profiles -> Mongo.

Also owns the browser session (login/checkpoint detection) and the payload
parsing (TikTokUser + friends): both are produced here first and re-used by
analysis_engine.py, which imports them rather than redefining them, so
there is exactly one definition of each across the two files.

WHY THIS DRIVES A REAL BROWSER RATHER THAN CALLING AN API DIRECTLY
    TikTok publishes no free, stable public API for search or profile
    lookup. Every "TikTok API" advertised online is either a paid reseller
    wrapping the same scraping this module does, or a raw replication of
    TikTok's own private request signing (X-Bogus, msToken, _signature),
    generated by TikTok's own JavaScript at runtime from browser
    fingerprinting, and changed on TikTok's own schedule, not ours.
    Reverse-engineering that signature is exactly the "breaks without
    warning every few months" maintenance burden every OTHER platform in
    this engine avoids by driving a real logged-in browser instead and
    letting the platform's own frontend do the signing for us (see
    stealth/browser.py). TikTok gets the same treatment here, not a
    different one.

WHERE THE DATA ACTUALLY COMES FROM, IN ORDER
    1. TikTok server-renders its own initial page state into a `<script>`
       tag on every page, `__UNIVERSAL_DATA_FOR_REHYDRATION__` on current
       builds, `SIGI_STATE` on older ones/behind experiments. A profile
       page's user info AND a search page's first batch of results both
       arrive this way, in the SAME response as the HTML, no XHR race to
       wait on. This is the primary source, and deliberately mirrors the
       hard lesson already learned in instagram/analysis_engine.py: passive
       network interception of a payload that may not fire reliably is not
       something to build the primary path around.
    2. Network responses matching TikTok's own `/api/search/...` calls,
       intercepted passively while scrolling, the second page of results
       onward arrives this way, since the hydration script only ever
       carries the first batch.
    3. When both of the above come up empty. TikTok strips the hydration
       payload from traffic its own bot-scoring doesn't like, leaving a
       skeleton page with no counts, this falls back to reading the
       rendered results directly: anchors linking to `/@<username>`, the
       one thing a results page cannot hide, since a clickable result IS a
       link to a profile.

NEEDS LIVE VERIFICATION. Every field name below (`uniqueId`, `avatarLarger`,
`followerCount`, ...) is reverse-engineered from public write-ups, not
captured from a live authenticated session the way every other platform's
parsing in this codebase was. The DOM fallback and the run_strategies chain
exist specifically so a wrong guess here degrades to fewer fields rather
than to zero results reported as a clean success, but this module should
not be trusted in production before a real session confirms it end to end
(see registry.py's `stability_note` for this platform).
"""

from __future__ import annotations

import asyncio
import json
import re
import sys
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Iterator, Optional
from urllib.parse import quote

from backend.shared.extraction import ExtractionResult, run_strategies
from backend.shared.logging import get_logger
from backend.shared.text import iter_dicts
from backend.stealth.browser import Session
from backend.platforms.facebook.discovery_engine import Hit

log = get_logger("tiktok")

# Session / login state
# The upload page requires a logged-in account. TikTok redirects anyone
# without one to /login, so it doubles as a clean authenticated probe the
# same way Instagram's /accounts/edit/ does. `expect_path` is the positive
# confirmation (see stealth/browser.py::Session.check_session's own
# docstring on why absence of a login string is not evidence of success).
UPLOAD_PROBE = "https://www.tiktok.com/upload?lang=en"

RE_LOGIN = re.compile(r"(Log in to TikTok|Sign up for TikTok|Use QR code to log in)", re.I)
RE_CHECKPOINT = re.compile(
    r"(verify to continue|select.{0,20}shapes|drag the slider|slide to verify|"
    r"unusual (login )?activity|security check|captcha)",
    re.I,
)
RE_GONE = re.compile(
    r"(couldn.t find this account|this account can.t be found|user doesn.t exist)", re.I,
)


class TikTokSession(Session):
    async def check_session(self) -> bool:  # type: ignore[override]
        return await super().check_session(
            UPLOAD_PROBE, RE_LOGIN, RE_CHECKPOINT, expect_path="/upload",
        )


# Payload parsing (profile extraction)


def _to_int(v: Any) -> Optional[int]:
    """Loose numeric coercion, counts arrive as either ints or strings
    depending on which of TikTok's own JSON shapes a given response uses."""
    if v is None:
        return None
    try:
        return int(v)
    except (TypeError, ValueError):
        return None


@dataclass
class TikTokUser:
    entity_id: str = ""
    username: str = ""
    nickname: str = ""
    avatar: str = ""
    bio: str = ""
    bio_link: str = ""
    verified: bool = False
    private: bool = False
    follower_count: Optional[int] = None
    following_count: Optional[int] = None
    # total likes across every video. TikTok's own reach figure, the
    # closest analogue another platform's follower count plays for "how far
    # could this impersonation spread"
    heart_count: Optional[int] = None
    video_count: Optional[int] = None
    last_post_iso: str = ""

    @property
    def url(self) -> str:
        return f"https://www.tiktok.com/@{self.username}" if self.username else ""

    @property
    def has_custom_pic(self) -> bool:
        return bool(self.avatar)


def user_from_node(user: dict, stats: Optional[dict] = None) -> Optional[TikTokUser]:
    """One `user`-shaped dict (+ its sibling `stats`/`statsV2` dict, if
    counts live separately rather than merged into `user` itself) ->
    TikTokUser."""
    if not isinstance(user, dict):
        return None
    username = user.get("uniqueId") or user.get("unique_id") or ""
    if not username:
        return None
    stats = stats if isinstance(stats, dict) else {}

    def stat(*keys: str) -> Optional[int]:
        for src in (stats, user):
            for k in keys:
                if k in src:
                    n = _to_int(src[k])
                    if n is not None:
                        return n
        return None

    raw_bio_link = user.get("bioLink") or {}
    bio_link = raw_bio_link.get("link", "") if isinstance(raw_bio_link, dict) else str(raw_bio_link or "")

    return TikTokUser(
        entity_id=str(user.get("id") or user.get("secUid") or ""),
        username=username,
        nickname=(user.get("nickname") or "").strip(),
        avatar=user.get("avatarLarger") or user.get("avatarMedium") or user.get("avatarThumb") or "",
        bio=(user.get("signature") or "").strip(),
        bio_link=bio_link.strip(),
        verified=bool(user.get("verified")),
        private=bool(user.get("privateAccount") or user.get("secret")),
        follower_count=stat("followerCount", "followers"),
        following_count=stat("followingCount", "following"),
        heart_count=stat("heartCount", "heart", "diggCount"),
        video_count=stat("videoCount"),
    )


def iter_users(blob: Any) -> Iterator[TikTokUser]:
    """Every user-shaped node in a hydration/search payload, deduped by
    username, in document order. Walks the whole tree rather than trusting
    one fixed path, see this module's docstring on the key layout already
    having moved once."""
    seen: set[str] = set()
    for d in iter_dicts(blob):
        nested = d.get("user")
        if isinstance(nested, dict) and nested.get("uniqueId"):
            stats = d.get("stats") if isinstance(d.get("stats"), dict) else d.get("statsV2")
            u = user_from_node(nested, stats if isinstance(stats, dict) else None)
        elif d.get("uniqueId"):
            u = user_from_node(d)
        else:
            continue
        if u and u.username.lower() not in seen:
            seen.add(u.username.lower())
            yield u


def profile_from(blob: Any, username: str = "") -> Optional[TikTokUser]:
    """The one user node in a payload matching `username`, or the first
    user node at all when no username is given to match against."""
    want = username.lower()
    for u in iter_users(blob):
        if not want or u.username.lower() == want:
            return u
    return None


# TikTok video ids are Snowflake-style: the top 32 bits are a Unix
# timestamp (seconds) of when the video was created, a documented,
# independently reproducible property of the id itself, unlike everything
# else in this module that depends on guessing a JSON key name correctly.
def _video_id_to_iso(video_id: Any) -> str:
    try:
        ts = int(video_id) >> 32
    except (TypeError, ValueError):
        return ""
    try:
        dt = datetime.fromtimestamp(ts, tz=timezone.utc)
    except (ValueError, OSError, OverflowError):
        return ""
    now = datetime.now(timezone.utc)
    # TikTok launched in 2016; a decoded stamp outside [launch, now] means
    # this wasn't actually a video id (or the id scheme assumption doesn't
    # hold for it), report nothing rather than a nonsense date
    return dt.date().isoformat() if 2016 <= dt.year and dt <= now else ""


def _epoch_to_iso(ts: Any) -> str:
    """A `createTime` value (real epoch seconds, straight off TikTok's own
    search JSON) -> ISO date, with the same launch-date/future sanity
    bounds as `_video_id_to_iso`."""
    n = _to_int(ts)
    if not n:
        return ""
    try:
        dt = datetime.fromtimestamp(n, tz=timezone.utc)
    except (ValueError, OSError, OverflowError):
        return ""
    now = datetime.now(timezone.utc)
    return dt.date().isoformat() if 2016 <= dt.year and dt <= now else ""


def newest_post_iso(blob: Any, username: str = "") -> str:
    """The newest video's date for one profile, decoded straight from its
    id (see `_video_id_to_iso`), deliberately not read off any "createTime"
    field, since that key's presence/name in TikTok's own JSON is far less
    certain than the id-encodes-a-timestamp property. Scoped to `username`
    when a video's author is identifiable, unscoped (best candidate found
    anywhere in the blob) otherwise, a hydration payload for one profile
    page should not carry any other author's videos, but this stays
    defensive rather than assuming that."""
    want = username.lower()
    best = ""
    for d in iter_dicts(blob):
        vid = d.get("id")
        if not vid or not isinstance(vid, (str, int)):
            continue
        # a video node's own shape: an author reference somewhere alongside
        # its id, OR (search/list contexts) a sibling "desc"/"video" field
        author = d.get("author")
        author_name = ""
        if isinstance(author, dict):
            author_name = (author.get("uniqueId") or "").lower()
        elif isinstance(author, str):
            author_name = author.lower()
        if want and author_name and author_name != want:
            continue
        if "desc" not in d and "video" not in d and "stats" not in d:
            continue  # not actually a video node, just something with an "id" key
        iso = _video_id_to_iso(vid)
        if iso and iso > best:
            best = iso
    return best


# Hydration script (primary source)

JS_HYDRATION = """
() => {
  const ids = ['__UNIVERSAL_DATA_FOR_REHYDRATION__', 'SIGI_STATE'];
  for (const id of ids) {
    const el = document.getElementById(id);
    if (el && el.textContent) return el.textContent;
  }
  return '';
}
"""


async def read_hydration(page) -> Any:
    """The page's own embedded initial-state JSON, or None when it's
    missing/unparseable, never raises, callers fall through to
    interception/DOM either way."""
    try:
        text = await page.evaluate(JS_HYDRATION)
    except Exception:
        return None
    if not text:
        return None
    try:
        return json.loads(text)
    except (json.JSONDecodeError, ValueError):
        return None


# DOM fallback
# Anchored on links to `/@<username>`, which is what a clickable search
# result IS regardless of anything else TikTok changes about the response
# shape or the surrounding markup, the same reasoning Facebook's own DOM
# fallback documents for anchoring on profile links there.
JS_DOM_SEARCH = """
() => {
  const seen = new Set();
  const out = [];
  for (const a of document.querySelectorAll('a[href^="/@"]')) {
    const href = a.getAttribute('href') || '';
    const m = href.match(/^\\/@([^/?]+)/);
    if (!m) continue;
    const username = m[1];
    if (seen.has(username.toLowerCase())) continue;
    seen.add(username.toLowerCase());
    const card = a.closest('div') || a;
    const img = a.querySelector('img') || card.querySelector('img');
    let name = '';
    for (const el of card.querySelectorAll('p, span, h3, h4')) {
      const t = (el.textContent || '').trim();
      if (t && t.toLowerCase() !== username.toLowerCase() && !t.startsWith('@')) { name = t; break; }
    }
    out.push({ username, name, avatar: img ? (img.getAttribute('src') || '') : '' });
  }
  return out;
}
"""


async def dom_users(page) -> list[TikTokUser]:
    """Scrape the rendered results feed. Used only when neither the
    hydration script nor an intercepted search response yielded anything.
    See Discovery.sweep."""
    rows = await page.evaluate(JS_DOM_SEARCH)
    users: list[TikTokUser] = []
    for r in rows or []:
        username = (r.get("username") or "").strip()
        if not username:
            continue
        users.append(TikTokUser(
            username=username,
            nickname=(r.get("name") or "").strip(),
            avatar=(r.get("avatar") or "").strip(),
        ))
    return users


def parse_lines(text: str) -> Iterator[Any]:
    """Most responses are a single JSON object; some stream as JSON lines."""
    text = (text or "").strip()
    if not text:
        return
    try:
        yield json.loads(text)
        return
    except (json.JSONDecodeError, ValueError):
        pass
    for line in text.splitlines():
        line = line.strip()
        if line.startswith("{"):
            try:
                yield json.loads(line)
            except (json.JSONDecodeError, ValueError):
                continue


# Crawling / pagination

SEARCH_URL = "https://www.tiktok.com/search?q={q}"

# LIVE-CONFIRMED (2026-08-11, against a real session): deep-linking straight
# into `/search/user?q=...` trips TikTok's bot detection, the page loads
# but its own results panel renders "Something went wrong / Sorry,
# something wrong with the server, please try again", no /api/search/*
# call ever fires, and the hydration payload carries nothing for the
# query. Landing on the plain `/search?q=...` URL (the Top tab, exactly
# where a person typing a query and hitting Enter actually lands) and then
# clicking the "Users" tab in-page, exactly what this JS does, behaves
# completely differently: the real `/api/search/general/full/` and
# `/api/search/general/preview/` calls fire immediately and the Users tab
# renders real results. Not spoofing anything extra to get there; simply
# not doing the one thing (a direct sub-tab deep link) that reads as
# non-human.
JS_CLICK_USERS_TAB = """
() => {
  const els = Array.from(document.querySelectorAll('[role="tab"], a, div, span, p'));
  const t = els.find(el => (el.textContent || '').trim() === 'Users' && el.offsetParent !== null);
  if (t) { t.click(); return true; }
  return false;
}
"""

JS_CLICK_VIDEOS_TAB = """
() => {
  const els = Array.from(document.querySelectorAll('[role="tab"], a, div, span, p'));
  const t = els.find(el => (el.textContent || '').trim() === 'Videos' && el.offsetParent !== null);
  if (t) { t.click(); return true; }
  return false;
}
"""


async def newest_post_via_search(ctx, username: str, timeout_s: float = 20.0) -> str:
    """The one CAPTCHA-free way found (live-confirmed 2026-08-11) to learn
    when an account last posted.

    Visiting a profile's OWN video grid to find this out repeatedly put
    the session behind TikTok's slide-verify challenge, the grid tiles
    render as empty placeholders, no `/api/post/item_list/` response ever
    carries a body, and this backend will never automate solving that
    challenge (out of scope on principle, not just difficulty). Searching
    the account's own username on the Videos tab is the SAME search
    surface `Discovery.sweep` already uses successfully, and never
    triggered the challenge across repeated live testing, likely because
    it's an ordinary keyword search, not a deep-link into one account's
    own content feed. TikTok's search response carries a real `createTime`
    (epoch seconds) directly on each video node, no id-decoding needed.

    NOT exhaustive: this is whatever TikTok's search ranks as relevant for
    the username as a query, not a full chronological listing of the
    account's posts, a thin/generic username may surface nothing even
    for an active account. A miss here is "this weaker signal didn't
    happen to find anything," never "confirmed inactive", callers must
    treat "" the same as any other unknown, not as evidence of dormancy.
    """
    if not username:
        return ""
    page = await ctx.new_page()
    responses: list[str] = []

    async def on_response(resp):
        if "/api/search/general/full" not in resp.url:
            return
        try:
            responses.append(await resp.text())
        except Exception:
            pass

    page.on("response", lambda r: asyncio.create_task(on_response(r)))
    try:
        await page.goto(
            SEARCH_URL.format(q=quote(username)), wait_until="domcontentloaded",
            timeout=int(timeout_s * 1000),
        )
        await page.wait_for_timeout(3000)
        for _ in range(4):
            if await page.evaluate(JS_CLICK_VIDEOS_TAB):
                break
            await page.wait_for_timeout(500)
        await page.wait_for_timeout(4000)

        want = username.lower()
        best_ts = 0
        for text in responses:
            for blob in parse_lines(text):
                for d in iter_dicts(blob):
                    author = d.get("author")
                    author_name = (author.get("uniqueId") or "").lower() if isinstance(author, dict) else ""
                    if author_name != want:
                        continue
                    ts = _to_int(d.get("createTime"))
                    if ts and ts > best_ts:
                        best_ts = ts
        return _epoch_to_iso(best_ts) if best_ts else ""
    except Exception:
        return ""
    finally:
        try:
            await page.close()
        except Exception:
            pass


@dataclass
class Sweep:
    keyword: str
    tab: str = "people"
    hits: list[Hit] = field(default_factory=list)
    users: list[TikTokUser] = field(default_factory=list)
    pages: int = 0
    stopped: str = ""  # exhausted | stalled | cap:* | error
    complete: bool = False
    seconds: float = 0.0
    error: str = ""
    # "hydration+network" normally; "dom" when both came up empty and the
    # rendered results page had to stand in
    source: str = "hydration+network"
    extraction: Optional[ExtractionResult] = None

    def summary(self) -> str:
        base = f"{len(self.hits)} hits, {self.pages} pages, {self.stopped}"
        return f"{base}, via {self.source}" if self.source != "hydration+network" else base


class Discovery:
    """Runs keyword sweeps on an already-started browser session."""

    def __init__(self, args, ctx):
        self.a = args
        self.ctx = ctx

    async def sweep(self, keyword: str, tab: str = "people") -> Sweep:
        out = Sweep(keyword=keyword, tab=tab)
        started = time.time()
        page = await self.ctx.new_page()

        by_username: dict[str, TikTokUser] = {}
        arrived = asyncio.Event()

        async def on_response(resp):
            try:
                if "/api/search/" not in resp.url:
                    return
                text = await resp.text()
            except Exception:
                return
            for blob in parse_lines(text):
                for u in iter_users(blob):
                    by_username.setdefault(u.username.lower(), u)
            out.pages += 1
            arrived.set()

        page.on("response", lambda r: asyncio.create_task(on_response(r)))

        try:
            await page.goto(
                SEARCH_URL.format(q=quote(keyword)), wait_until="domcontentloaded",
                timeout=self.a.timeout * 1000,
            )
            try:
                await page.wait_for_function(
                    "() => document.body.innerText.length > 400", timeout=self.a.settle * 1000,
                )
            except Exception:
                pass

            # Land on Top (the default tab) like a person would, THEN click
            # into Users, see SEARCH_URL's own comment on why the direct
            # deep-link doesn't work. A couple of retries: the tab element
            # may not be mounted yet the instant innerText clears 400 chars.
            clicked = False
            for _ in range(4):
                if await page.evaluate(JS_CLICK_USERS_TAB):
                    clicked = True
                    break
                await page.wait_for_timeout(500)
            if not clicked:
                log.warning(f"tiktok/people {keyword!r}: could not find the Users tab to click")

            # The first batch of results may already be in the hydration
            # payload embedded at load, try it before waiting on any XHR,
            # same reasoning as the profile page (see module docstring).
            hydration = await read_hydration(page)
            if hydration:
                for u in iter_users(hydration):
                    by_username.setdefault(u.username.lower(), u)

            if not by_username:
                try:
                    await asyncio.wait_for(arrived.wait(), timeout=self.a.settle)
                except asyncio.TimeoutError:
                    pass

            stalls = 0
            while True:
                if self.a.max_results and len(by_username) >= self.a.max_results:
                    out.stopped = "cap:results"
                    break
                if self.a.max_pages and out.pages >= self.a.max_pages:
                    out.stopped = "cap:pages"
                    break
                if self.a.max_seconds and time.time() - started >= self.a.max_seconds:
                    out.stopped = "cap:seconds"
                    break

                before = len(by_username)
                arrived.clear()
                await page.evaluate("window.scrollTo(0, document.body.scrollHeight)")
                try:
                    await asyncio.wait_for(arrived.wait(), timeout=self.a.page_wait)
                except asyncio.TimeoutError:
                    pass

                if len(by_username) > before:
                    stalls = 0
                    if out.pages and out.pages % self.a.progress_every == 0:
                        print(
                            f"    [tiktok/{tab}] {keyword!r}: {len(by_username)} so far, "
                            f"page {out.pages}, {time.time()-started:.0f}s",
                            file=sys.stderr,
                        )
                else:
                    stalls += 1
                    if stalls >= self.a.patience:
                        out.stopped, out.complete = "stalled", False
                        break
                    await page.wait_for_timeout(600)

            # Hydration + intercepted network first (richer, real counts).
            # Rendered DOM second, only when both produced nothing at all:
            # a healthy sweep never pays for the DOM pass, and when
            # TikTok's payload shape rotates, discovery degrades to "fewer
            # fields" instead of to "zero results, reported as success".
            chain = await run_strategies(
                f"tiktok/search[{keyword!r}]",
                [
                    ("hydration+network", lambda: list(by_username.values())),
                    ("dom:profile-links", lambda: dom_users(page)),
                ],
            )
            out.users = chain.value or []
            out.extraction = chain
            if chain.degraded:
                out.source = "dom"

            out.hits = [
                Hit(
                    entity_id=u.entity_id or u.username,
                    name=u.nickname or u.username,
                    url=u.url,
                    avatar=u.avatar,
                    has_custom_pic=u.has_custom_pic,
                    verified=u.verified,
                    entity_type="profile",
                    keyword=keyword,
                    tab=tab,
                    rank=i,
                    source=out.source,
                )
                for i, u in enumerate(out.users)
                if u.url
            ]
            if self.a.max_results:
                out.hits = out.hits[: self.a.max_results]
        except Exception as e:
            out.stopped, out.error = "error", f"{type(e).__name__}: {e}"
        finally:
            try:
                await page.close()
            except Exception:
                pass
            out.seconds = time.time() - started
        return out

    async def run(self, keywords: list[str], tabs: Optional[list[str]] = None) -> list[Sweep]:
        """TikTok has one people-search surface, so `tabs` is accepted and ignored."""
        sem = asyncio.Semaphore(max(1, self.a.concurrency))

        async def one(i: int, keyword: str) -> tuple[int, Sweep]:
            async with sem:
                await asyncio.sleep(i % max(1, self.a.concurrency) * 1.0)
                s = await self.sweep(keyword)
                print(
                    f"  [tiktok/people] {keyword!r}: {s.summary()} ({s.seconds:.1f}s)",
                    file=sys.stderr,
                )
                return i, s

        pairs = await asyncio.gather(*(one(i, k) for i, k in enumerate(keywords)))
        return [s for _, s in sorted(pairs, key=lambda p: p[0])]
